# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nubia/msm8998-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter nx563j nx595j,$(TARGET_DEVICE)),)

endif
