# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nubia/nx563j-prebuilt/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/br_netfilter.ko:system/lib/modules/br_netfilter.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/mpq-adapter.ko:system/lib/modules/mpq-adapter.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/mpq-dmx-hw-plugin.ko:system/lib/modules/mpq-dmx-hw-plugin.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/multi_channel_hook.ko:system/lib/modules/multi_channel_hook.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/rdbg.ko:system/lib/modules/rdbg.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/test-iosched.ko:system/lib/modules/test-iosched.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/texfat.ko:system/lib/modules/texfat.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/tspp.ko:system/lib/modules/tspp.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/ufs_test.ko:system/lib/modules/ufs_test.ko \
    vendor/nubia/nx563j-prebuilt/proprietary/lib/modules/wil6210.ko:system/lib/modules/wil6210.ko
